version: "3"

services:
  nginx:
    build: "./ui"
    ports:
      - "${NGINX_PORT}:80"
  db:
    build: "./db"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: speedtest
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/mysql_data:/var/lib/mysql
