version: "3"

services:
  api:
    build:
      context: "./api"
      args:
        - PORT=${API_PORT}
        - DATABASE_DATASOURCE=${API_DATABASE_DATASOURCE}
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - "nginx"
  nginx:
    build: 
      context: "./ui"
      args:
        - TEST=${REACT_APP_TEST}
        - API_URL=${REACT_APP_URL}
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - "db"
  db:
    build: "./db"
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql_data:/var/lib/mysql
